apiVersion: apps/v1
kind: Deployment
metadata:
  name: keystone-service
  labels:
    app: keystone
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: keystone
  template:
    metadata:
      labels:
        app: keystone
      annotations:
        kubernetes.io/change-cause: "Updated to 399600302704.dkr.ecr.ap-south-1.amazonaws.com/greatify-auth-service:6fa427de9e4e9f540c2728587b28b5983e7e3c59-Update-Dockerfile-to-execute-s"
    spec:
      serviceAccountName: keystone-sa
      volumes:
      - name: keystone-secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: keystone-secrets
      - name: keystone-global-nginx-config
        configMap:
          name: keystone-nginx-config
      - name: keystone-server-config
        configMap:
          name: keystone-nginx-config
          items:
            - key: default.conf
              path: default.conf
      containers:
      - name: keystone
        image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/greatify-auth-service:6fa427de9e4e9f540c2728587b28b5983e7e3c59-Update-Dockerfile-to-execute-s
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
        - name: keystone-secrets
          mountPath: /app/.env
          subPath: .env
        - name: keystone-global-nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: keystone-server-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf