apiVersion: apps/v1
kind: Deployment
metadata:
  name: keystone-celery-service
  labels:
    app: keystone-celery
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: keystone-celery
  template:
    metadata:
      labels:
        app: keystone-celery
      annotations:
        kubernetes.io/change-cause: "Updated to "
    spec:
      serviceAccountName: keystone-sa
      volumes:
      - name: keystone-secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: keystone-secrets
      containers:
      - name: keystone-celery
        image: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/greatify-auth-service:6fa427de9e4e9f540c2728587b28b5983e7e3c59-Update-Dockerfile-to-execute-s
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        volumeMounts:
        - name: keystone-secrets
          mountPath: /app/.env
          subPath: .env